pip install discord
pip install dateparser
pip install beautifulsoup4
pip install pytz
pip install requests
pip install greenlet
pip install wolframalpha
pip install PyDictionary
pip install pyimgur
pip install wolframalpha
pip install pillow
pip install googletrans
pip install urbandict
