pip3 install discord
pip3 install dateparser
pip3 install beautifulsoup4
pip3 install pytz
pip3 install requests
pip3 install greenlet
pip3 install wolframalpha
pip3 install PyDictionary
pip3 install pyimgur
pip3 install wolframalpha
pip3 install pillow
pip3 install googletrans
